var car="Civic";
console.log(car == "Civic"? true:false);

var bike="yamaha";
console.log(bike== "honda"? true:false);

var fruit="mango";
console.log(fruit== "mango"? true:false);

var city="lahore";
console.log(city== "karachi"? true:false);

var PIAIC="great initiative";
console.log(PIAIC== "great initiative"? true:false);

var FOOD="LOVE";
console.log(FOOD== "LOVE"? true:false);

var bike="yamaha";
console.log(bike== "honda"? true:false);

var Khana="kabab";
console.log(Khana== "biryani"? true:false);

var sialkot="village";
console.log(sialkot== "sports"? true:false);

var vegetable="tomato";
console.log(vegetable== "tomato"? true:false);